# .github/workflows/reusable/cogutil.yml

name: Reusable CogUtil Workflow

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  cogutil_job:
    name: CogUtil Job
    runs-on: ubuntu-latest
    steps:
      - name: Setup Build Environment
        uses: ./.github/actions/setup-build
        with:
          branch: ${{ inputs.branch }}
        env:
          CCACHE_DIR: /ws/ccache
          MAKEFLAGS: -j2
