# .github/workflows/reusable/cogutil.yml

name: Reusable CogUtil Workflow

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  cogutil_job:
    name: CogUtil Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Set Up Environment
        run: |
          echo "MAKEFLAGS=-j2" >> $GITHUB_ENV
          export CCACHE_DIR=/ws/ccache

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run Tests
        run: |
          cd build
          make test

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cogutil-build
          path: build/
