name: Improved CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cogutil:
    uses: ./.github/workflows/reusable/build-component.yml
    with:
      component-name: cogutil
      repository: opencog/cogutil
      artifact-paths: |
        /usr/local/lib/libcogutil*
        /usr/local/include/cogutil/

  atomspace:
    needs: cogutil
    uses: ./.github/workflows/reusable/build-component.yml
    with:
      component-name: atomspace
      repository: opencog/atomspace
      dependencies: cogutil-artifacts
      artifact-paths: |
        /usr/local/lib/libatomspace*
        /usr/local/include/atomspace/

  ure:
    needs: atomspace
    uses: ./.github/workflows/reusable/build-component.yml
    with:
      component-name: ure
      repository: opencog/ure
      dependencies: cogutil-artifacts,atomspace-artifacts
      artifact-paths: |
        /usr/local/lib/libure*
        /usr/local/include/ure/

  asmoses:
    needs: atomspace
    uses: ./.github/workflows/reusable/build-component.yml
    with:
      component-name: asmoses
      repository: opencog/asmoses
      dependencies: cogutil-artifacts,atomspace-artifacts

  unify:
    needs: ure
    uses: ./.github/workflows/reusable/build-component.yml
    with:
      component-name: unify
      repository: opencog/unify
      dependencies: cogutil-artifacts,atomspace-artifacts,ure-artifacts

  attention:
    needs: atomspace
    uses: ./.github/workflows/reusable/build-component.yml
    with:
      component-name: attention
      repository: opencog/attention
      dependencies: cogutil-artifacts,atomspace-artifacts

  cogserver:
    needs: atomspace
    uses: ./.github/workflows/reusable/build-component.yml
    with:
      component-name: cogserver
      repository: opencog/cogserver
      dependencies: cogutil-artifacts,atomspace-artifacts

  miner:
    needs: [atomspace, ure]
    uses: ./.github/workflows/reusable/build-component.yml
    with:
      component-name: miner
      repository: opencog/miner
      dependencies: cogutil-artifacts,atomspace-artifacts,ure-artifacts

  opencog:
    needs: [atomspace, ure, cogserver, attention]
    uses: ./.github/workflows/reusable/build-component.yml
    with:
      component-name: opencog
      repository: opencog/opencog
      dependencies: cogutil-artifacts,atomspace-artifacts,ure-artifacts,cogserver-artifacts,attention-artifacts

  integration-test:
    name: Integration Tests
    needs: [opencog, miner, asmoses, unify]
    runs-on: ubuntu-latest
    container:
      image: opencog/opencog-deps
      options: --user root
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: /usr/local/
      
      - name: Run integration tests
        run: |
          # Add integration test commands here
          echo "Running integration tests..."
          ldconfig
          # Example: python -m pytest tests/integration/

  package:
    name: Package All Components
    needs: [opencog, miner, asmoses, unify]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    container:
      image: opencog/opencog-deps
      options: --user root
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: /usr/local/
      
      - name: Create distribution package
        run: |
          ldconfig
          mkdir -p dist
          # Create a tarball with all components
          tar -czf dist/opencog-complete-$(date +%Y%m%d-%H%M%S).tar.gz \
            /usr/local/lib/lib* \
            /usr/local/include/ \
            /usr/local/share/opencog/ || true
      
      - name: Upload distribution
        uses: actions/upload-artifact@v4
        with:
          name: opencog-distribution
          path: dist/
          retention-days: 7