# .github/workflows/ci-org-v3.yml

name: CI Org v3

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CCACHE_DIR: /ws/ccache
  MAKEFLAGS: -j2

jobs:
  build-and-test:
    name: Build and Test All Components
    runs-on: ubuntu-latest
    container:
      image: opencog/opencog-deps
      options: --user root
      env:
        CCACHE_DIR: /ws/ccache

    services:
      opencog-postgres:
        image: opencog/postgres
        env:
          POSTGRES_USER: opencog_test
          POSTGRES_PASSWORD: cheese
          POSTGRES_DB: opencog_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # 1. Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Configure Git Safe Directory
      - name: Configure Git Safe Directory
        run: git config --global --add safe.directory /__w/opencog-central/opencog-central

      # 3. Setup ccache Cache
      - name: Setup ccache Cache
        uses: actions/cache@v4
        with:
          path: /ws/ccache
          key: ccache-build-${{ runner.os }}-${{ hashFiles('**/*') }}
          restore-keys: |
            ccache-build-

      # 4. Set MAKEFLAGS
      - name: Set MAKEFLAGS
        run: echo "MAKEFLAGS=-j2" >> $GITHUB_ENV

      # 5. Install Dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ccache pkg-config

      # 6. Build and Install CogUtil
      - name: Build and Install CogUtil
        run: |
          mkdir -p cogutil/build
          cd cogutil/build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make
          sudo make install
          sudo ldconfig

      # 7. Verify CogUtil Installation
      - name: Verify CogUtil Installation
        run: |
          pkg-config --cflags cogutil || { echo "CogUtil not found in pkg-config"; exit 1; }
          pkg-config --libs cogutil || { echo "CogUtil libraries not found"; exit 1; }

      # 8. Build and Install AtomSpace
      - name: Build and Install AtomSpace
        run: |
          mkdir -p atomspace/build
          cd atomspace/build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/local ..
          make
          sudo make install
          sudo ldconfig

      # 9. Run AtomSpace Tests
      - name: Run AtomSpace Tests
        run: |
          cd atomspace/build
          make tests
          make check ARGS="$MAKEFLAGS"

      # 10. Print AtomSpace Test Log
      - name: Print AtomSpace Test Log
        if: always()
        run: |
          cat atomspace/build/tests/Testing/Temporary/LastTest.log || echo "Test log not found."

      # 11. (Optional) Repeat Steps 6-10 for Other Components
      # Example: Build and Install CogServer
      - name: Build and Install CogServer
        run: |
          mkdir -p cogserver/build
          cd cogserver/build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/local ..
          make
          sudo make install
          sudo ldconfig

      # Run CogServer Tests
      - name: Run CogServer Tests
        run: |
          cd cogserver/build
          make tests
          make check ARGS="$MAKEFLAGS"

      # Print CogServer Test Log
      - name: Print CogServer Test Log
        if: always()
        run: |
          cat cogserver/build/tests/Testing/Temporary/LastTest.log || echo "Test log not found."

      # Similarly, add steps for attention, unify, ure, miner, asmoses, opencog

      # 12. Build and Install OpenCog
      - name: Build and Install OpenCog
        run: |
          mkdir -p opencog/build
          cd opencog/build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/local ..
          make
          sudo make install
          sudo ldconfig

      # Run OpenCog Tests
      - name: Run OpenCog Tests
        run: |
          cd opencog/build
          make tests
          make check ARGS="$MAKEFLAGS"

      # Print OpenCog Test Log
      - name: Print OpenCog Test Log
        if: always()
        run: |
          cat opencog/build/tests/Testing/Temporary/LastTest.log || echo "Test log not found."

      # 13. (Optional) Package Artifacts
      - name: Package OpenCog
        if: github.ref == 'refs/heads/main'
        run: |
          cd opencog/build
          make package || echo "Package target not defined."

      # 14. (Optional) Upload Test Logs or Packages
      - name: Upload Test Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: |
            atomspace/build/tests/Testing/Temporary/LastTest.log
            cogserver/build/tests/Testing/Temporary/LastTest.log
            opencog/build/tests/Testing/Temporary/LastTest.log
          # Add other logs as needed

      - name: Upload Packages
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: opencog-packages
          path: opencog/build/packages/ || echo "No packages to upload."
