name: Consolidate AtomSpace Folders

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  consolidate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create orch-atomspace Directory
        run: mkdir -p orch-atomspace

      - name: Move atomspace Folders to orch-atomspace
        run: |
          mv atomspace orch-atomspace/
          mv atomspace-agents orch-atomspace/
          mv atomspace-bridge orch-atomspace/
          mv atomspace-cog orch-atomspace/
          mv atomspace-dht orch-atomspace/
          mv atomspace-explorer orch-atomspace/
          mv atomspace-ipfs orch-atomspace/
          mv atomspace-js orch-atomspace/
          mv atomspace-metta orch-atomspace/
          mv atomspace-restful orch-atomspace/
          mv atomspace-rocks orch-atomspace/
          mv atomspace-rpc orch-atomspace/
          mv atomspace-typescript orch-atomspace/
          mv atomspace-websockets orch-atomspace/
