# .github/workflows/main.yml

name: Main CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CCACHE_DIR: /ws/ccache
  MAKEFLAGS: -j2

jobs:
  cogutil:
    uses: ./.github/workflows/cogutil.yml
    with:
      branch: main
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  atomspace:
    needs: cogutil
    uses: ./.github/workflows/reusable/atomspace.yml
    with:
      branch: main
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cogserver:
    needs: atomspace
    uses: ./.github/workflows/reusable/cogserver.yml
    with:
      branch: main
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  opencog:
    needs: cogserver
    uses: ./.github/workflows/reusable/opencog.yml
    with:
      branch: main
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  asmoses:
    needs: opencog
    uses: ./.github/workflows/reusable/asmoses.yml
    with:
      branch: main
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ure:
    needs: asmoses
    uses: ./.github/workflows/reusable/ure.yml
    with:
      branch: main
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  unify:
    needs: ure
    uses: ./.github/workflows/reusable/unify.yml
    with:
      branch: main
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  package:
    needs: unify
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/reusable/package.yml
    with:
      branch: main
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
