name: Read Repositories

on:
  workflow_call:

jobs:
  read-repos:
    runs-on: ubuntu-latest

    steps:
    - name: Download repo_list.txt
      uses: actions/download-artifact@v2
      with:
        name: repo_list

    - name: Read repository list
      id: read-repos
      run: |
        REPO_LIST=$(cat repo_list.txt | tr '\n' ' ')
        echo "REPO_LIST=$REPO_LIST" >> $GITHUB_ENV
        echo "::set-output name=repo_list::$REPO_LIST"
