name: Sync Repositories

on:
  workflow_call:
    inputs:
      org_name:
        required: true
        type: string

jobs:
  sync-repos:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout central repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup git authentication and user
      run: |
        git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Create new branch
      run: |
        git checkout -b ${{ inputs.org_name }}

    - name: Download repo_list.txt
      uses: actions/download-artifact@v2
      with:
        name: repo_list

    - name: Read repository list
      run: |
        REPO_LIST=$(cat repo_list.txt | tr '\n' ' ')
        echo "REPO_LIST=$REPO_LIST" >> $GITHUB_ENV
        echo "Repository list: $REPO_LIST"

    - name: Print REPO_LIST
      run: |
        echo "REPO_LIST: $REPO_LIST"

    - name: Sync repositories
      run: |
        echo "REPO_LIST in sync step: $REPO_LIST"
        for REPO in $REPO_LIST; do
          if [ "$REPO" = ".github" ]; then
            echo "Skipping .github repository..."
            continue
          fi
          echo "Processing $REPO..."
          git clone "https://github.com/opencog/$REPO.git" "$REPO"
          cd "$REPO"
          git remote rm origin
          cd ..
          git add "$REPO"
          git commit -m "Add $REPO repository as a subfolder"
        done

    - name: Pull latest changes
      run: |
        git pull origin main --rebase

    - name: List directories
      run: |
        ls -la

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/ZoneCog/opencog-central.git" ${{ inputs.org_name }}
