name: Build, Test, and Install

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#      - name: Set up environment
 #       run: |
 #         sudo apt-get update
 #         sudo apt-get install -y build-essential cmake libboost-all-dev
          # Install CogUtil
 #         git clone https://github.com/opencog/cogutil.git
#          cd cogutil
  #        cd build
  #        cmake ..
 #         make
  #        sudo make install

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure CMake
        run: |
          cd build
          cmake -DCMAKE_PREFIX_PATH=/usr/local ..

      - name: Build
        run: |
          cd build
          make

      - name: Build tests
        run: |
          cd build
          make tests

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run tests
        run: |
          cd build
          make check

      - name: Print test log
        run: |
          cat build/tests/Testing/Temporary/LastTest.log

  install:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Install
        run: |
          cd build
          sudo make install

  package:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Build Debian package
        run: |
          cd build
          sudo make package

      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: build/packages/
